### PR TITLE
V2

### PR DESCRIPTION
**Pull request by hadim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hadim** [comment]
@conda-forge/help-go according to the official instructions, the binary should be put under `$PREFIX/lib/docker/cli-plugins` or `$PREFIX/libexec/docker/cli-plugins` (https://github.com/docker/compose/blob/aeb835a525bbafb0784161886bfcaa4008ca7ba5/README.md#linux).

What would you recommend here? Making a symlink from lib/libexec to `PREFIX/bin`? What about Windows (or should I disable windows for that package?)?

**Comment by marcelotrevisani** [comment]
@conda-forge-admin please rerender

**Comment by xmnlab** [comment]
probably it is not the same of what is intended by this PR, but I would like to share that here as well.

We create a package on pypi called compose-go (https://pypi.org/project/docker-compose/). basically it is a wrap for the docker-compose v2.

I was creating a conda-forge package for that here https://github.com/conda-forge/staged-recipes/pull/24466
but I am totally fine for closing that in favor of this v2 here.

**Comment by xmnlab** [comment]
I can help here .. but I will have time for that just in 1 week ... if that is ok .. I would be glad to help

**Comment by RaulPPelaez** [comment]
Hi, just bumping this since I have some interest in it. I gave it a try locally but did not get too far...

**Comment by xmnlab** [comment]
I am really packed here ... sorry but I will not be able to help too much here :(

**Comment by AdrianFreundQC** [comment]
> @conda-forge/help-go according to the official instructions, the binary should be put under `$PREFIX/lib/docker/cli-plugins` or `$PREFIX/libexec/docker/cli-plugins` (https://github.com/docker/compose/blob/aeb835a525bbafb0784161886bfcaa4008ca7ba5/README.md#linux).
> 
> What would you recommend here? Making a symlink from lib/libexec to `PREFIX/bin`? What about Windows (or should I disable windows for that package?)?

Installing to `libexec/docker/cli-plugins` is for installing it as a plugin (so you can run `docker compose`). That would probably not work with conda anyways, as your docker engine most likely won't be installed from conda and therefor not search your conda prefix for plugins.

I would recommend just going the [Standalone Install](https://docs.docker.com/compose/install/standalone/) route and installing it to `bin/docker-compose`, so users can run `docker-compose`, just as with compose v1.

**Pull request closed without merging**
